import { useState } from 'react'
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, Alert } from 'react-native'
import { router } from 'expo-router'
import { Colors, FontSize, Radius, Shadow } from '@/constants/theme'

const SUMMARY_ROWS = [
  { label: 'Billing Cycle',         value: 'May 15 – Jun 15, 2026' },
  { label: 'Zone',                   value: 'Banaba West – Zone 2'  },
  { label: 'Assigned Consumers',     value: '48'                    },
  { label: 'Readings Completed',     value: '42'                    },
  { label: 'Pending',                value: '6'                     },
  { label: 'Total Consumption',      value: '3,184 m³'              },
  { label: 'Average per Consumer',   value: '75.8 m³'               },
  { label: 'Highest Reading',        value: 'ACC-00231 · 85 m³'     },
  { label: 'Lowest Reading',         value: 'ACC-00312 · 58 m³'     },
  { label: 'Total Billed Amount',    value: '₱ 284,620.00'          },
  { label: 'Generated By',           value: 'Meter Reader'          },
  { label: 'Generated On',           value: new Date().toLocaleDateString('en-PH', { month: 'long', day: 'numeric', year: 'numeric' }) },
]

const TOP_CONSUMERS = [
  { rank: 1, name: 'Ana Dela Cruz',       acct: 'ACC-00231', usage: '85 m³', amount: '₱7,820' },
  { rank: 2, name: 'Maria Santos',        acct: 'ACC-00142', usage: '78 m³', amount: '₱7,120' },
  { rank: 3, name: 'Lourdes Bautista',    acct: 'ACC-00198', usage: '72 m³', amount: '₱6,540' },
  { rank: 4, name: 'Jose Reyes',          acct: 'ACC-00087', usage: '68 m³', amount: '₱6,150' },
  { rank: 5, name: 'Roberto Villanueva',  acct: 'ACC-00055', usage: '60 m³', amount: '₱5,420' },
]

export default function ExportReportScreen() {
  const [downloading, setDownloading] = useState(false)

  function handleDownload() {
    setDownloading(true)
    setTimeout(() => {
      setDownloading(false)
      Alert.alert(
        'Report Downloaded',
        'Monthly_Reading_Report_May2026.pdf has been saved to your Downloads folder.',
        [{ text: 'OK' }]
      )
    }, 1800)
  }

  return (
    <View style={styles.root}>
      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerBlob} />
        <TouchableOpacity style={styles.backBtn} onPress={() => router.back()} activeOpacity={0.8}>
          <Text style={styles.backIcon}>←</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Export Reports</Text>
        <Text style={styles.headerSub}>Monthly reading summary — May 2026</Text>
      </View>

      <ScrollView style={styles.body} showsVerticalScrollIndicator={false}>

        {/* Preview label */}
        <View style={styles.previewBanner}>
          <Text style={styles.previewIcon}>👁</Text>
          <Text style={styles.previewText}>Report Preview — read-only</Text>
        </View>

        {/* Summary card */}
        <View style={styles.reportCard}>
          <View style={styles.reportHeader}>
            <Text style={styles.reportBrand}>BWRWSAI</Text>
            <Text style={styles.reportBrandSub}>Monthly Reading Summary Report</Text>
          </View>
          <View style={styles.divider} />

          {SUMMARY_ROWS.map((row, i) => (
            <View
              key={row.label}
              style={[styles.summaryRow, i === SUMMARY_ROWS.length - 1 && { borderBottomWidth: 0 }]}
            >
              <Text style={styles.summaryLabel}>{row.label}</Text>
              <Text style={styles.summaryValue}>{row.value}</Text>
            </View>
          ))}
        </View>

        {/* Top consumers table */}
        <Text style={styles.sectionTitle}>Top 5 Consumers by Usage</Text>
        <View style={styles.tableCard}>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableHead, { flex: 0.4 }]}>#</Text>
            <Text style={[styles.tableHead, { flex: 2 }]}>Consumer</Text>
            <Text style={[styles.tableHead, { flex: 1, textAlign: 'right' }]}>Usage</Text>
            <Text style={[styles.tableHead, { flex: 1, textAlign: 'right' }]}>Amount</Text>
          </View>
          {TOP_CONSUMERS.map((c) => (
            <View key={c.rank} style={styles.tableRow}>
              <View style={[styles.rankBadge, { marginRight: 8 }]}>
                <Text style={styles.rankText}>{c.rank}</Text>
              </View>
              <View style={{ flex: 2 }}>
                <Text style={styles.tableName}>{c.name}</Text>
                <Text style={styles.tableAcct}>{c.acct}</Text>
              </View>
              <Text style={[styles.tableValue, { flex: 1, textAlign: 'right' }]}>{c.usage}</Text>
              <Text style={[styles.tableValue, { flex: 1, textAlign: 'right', color: Colors.primary }]}>{c.amount}</Text>
            </View>
          ))}
        </View>

        {/* Completion donut summary */}
        <View style={styles.completionCard}>
          <View style={styles.completionLeft}>
            <Text style={styles.completionPct}>87.5%</Text>
            <Text style={styles.completionLabel}>Completion Rate</Text>
          </View>
          <View style={styles.completionRight}>
            <View style={styles.completionItem}>
              <View style={[styles.completionDot, { backgroundColor: Colors.success }]} />
              <Text style={styles.completionItemText}>42 Completed</Text>
            </View>
            <View style={styles.completionItem}>
              <View style={[styles.completionDot, { backgroundColor: Colors.warning }]} />
              <Text style={styles.completionItemText}>6 Pending</Text>
            </View>
            <View style={styles.completionItem}>
              <View style={[styles.completionDot, { backgroundColor: Colors.primary }]} />
              <Text style={styles.completionItemText}>48 Total</Text>
            </View>
          </View>
        </View>

        {/* Download button */}
        <TouchableOpacity
          style={[styles.downloadBtn, downloading && styles.downloadBtnLoading]}
          onPress={handleDownload}
          activeOpacity={0.88}
          disabled={downloading}
        >
          <Text style={styles.downloadIcon}>{downloading ? '⏳' : '↓'}</Text>
          <Text style={styles.downloadText}>
            {downloading ? 'Generating PDF…' : 'Download Report (PDF)'}
          </Text>
        </TouchableOpacity>

        <View style={{ height: 32 }} />
      </ScrollView>
    </View>
  )
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: Colors.background },
  header: {
    backgroundColor: Colors.primary,
    paddingTop: 52, paddingBottom: 24, paddingHorizontal: 20, overflow: 'hidden',
  },
  headerBlob: {
    position: 'absolute', width: 180, height: 180,
    borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.08)',
    top: -50, right: -30,
  },
  backBtn: {
    width: 38, height: 38, borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center', justifyContent: 'center', marginBottom: 14,
  },
  backIcon: { fontSize: 18, color: Colors.white, fontWeight: '700' },
  headerTitle: { fontSize: FontSize.xxl, fontWeight: '900', color: Colors.white, marginBottom: 4 },
  headerSub: { fontSize: FontSize.sm, color: 'rgba(255,255,255,0.7)' },
  body: { flex: 1, padding: 16 },
  previewBanner: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    backgroundColor: '#e8f0fe', borderRadius: Radius.sm,
    padding: 10, marginBottom: 16,
    borderWidth: 1, borderColor: '#c7d9fb',
  },
  previewIcon: { fontSize: 14 },
  previewText: { fontSize: FontSize.xs, fontWeight: '700', color: Colors.primary },
  reportCard: {
    backgroundColor: Colors.white, borderRadius: Radius.md,
    padding: 18, marginBottom: 16,
    borderWidth: 1, borderColor: Colors.border, ...Shadow.sm,
  },
  reportHeader: { alignItems: 'center', marginBottom: 14 },
  reportBrand: { fontSize: FontSize.xl, fontWeight: '900', color: Colors.primary, letterSpacing: 2 },
  reportBrandSub: { fontSize: FontSize.xs, color: Colors.textMuted, marginTop: 2 },
  divider: { height: 1, backgroundColor: Colors.border, marginBottom: 12 },
  summaryRow: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: Colors.border,
  },
  summaryLabel: { fontSize: FontSize.sm, color: Colors.textSecondary, flex: 1 },
  summaryValue: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.textPrimary, textAlign: 'right', flex: 1 },
  sectionTitle: { fontSize: FontSize.sm, fontWeight: '800', color: Colors.textSecondary, marginBottom: 10 },
  tableCard: {
    backgroundColor: Colors.white, borderRadius: Radius.md,
    borderWidth: 1, borderColor: Colors.border, ...Shadow.sm,
    overflow: 'hidden', marginBottom: 16,
  },
  tableHeader: {
    flexDirection: 'row', alignItems: 'center',
    backgroundColor: '#f0f4ff', paddingHorizontal: 14, paddingVertical: 10,
    borderBottomWidth: 1, borderBottomColor: Colors.border,
  },
  tableHead: { fontSize: FontSize.xs, fontWeight: '800', color: Colors.textSecondary, textTransform: 'uppercase' },
  tableRow: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 14, paddingVertical: 11,
    borderBottomWidth: 1, borderBottomColor: Colors.border,
  },
  rankBadge: {
    width: 24, height: 24, borderRadius: 8,
    backgroundColor: '#e8f0fe', alignItems: 'center', justifyContent: 'center',
  },
  rankText: { fontSize: FontSize.xs, fontWeight: '800', color: Colors.primary },
  tableName: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.textPrimary },
  tableAcct: { fontSize: FontSize.xs, color: Colors.textMuted },
  tableValue: { fontSize: FontSize.sm, fontWeight: '700', color: Colors.textPrimary },
  completionCard: {
    flexDirection: 'row', backgroundColor: Colors.white, borderRadius: Radius.md,
    padding: 18, marginBottom: 20,
    borderWidth: 1, borderColor: Colors.border, ...Shadow.sm,
  },
  completionLeft: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRightWidth: 1, borderRightColor: Colors.border },
  completionPct: { fontSize: FontSize.xxxl, fontWeight: '900', color: Colors.success },
  completionLabel: { fontSize: FontSize.xs, color: Colors.textMuted, marginTop: 4 },
  completionRight: { flex: 1.5, paddingLeft: 18, gap: 10, justifyContent: 'center' },
  completionItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  completionDot: { width: 10, height: 10, borderRadius: 99 },
  completionItemText: { fontSize: FontSize.sm, fontWeight: '600', color: Colors.textPrimary },
  downloadBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10,
    backgroundColor: Colors.warning, borderRadius: Radius.md,
    height: 54, ...Shadow.md,
  },
  downloadBtnLoading: { opacity: 0.75 },
  downloadIcon: { fontSize: 20, color: Colors.white },
  downloadText: { fontSize: FontSize.md, fontWeight: '700', color: Colors.white },
})
